export const data = [
    {
        id: 1,
        name: "Manchester United",
        country: "England",
        league: "Premier League",
        titles: 20,
        founded: 1878,
        colors: ["#DA291C", "#FFFFFF"],
        badge: "https://api.promiedos.com.ar/images/team/baf/1",
        location: { lat: 53.4631, lng: -2.2913 },
    },
    {
        id: 2,
        name: "Manchester City",
        country: "England",
        league: "Premier League",
        titles: 9,
        founded: 1880,
        colors: ["#6CABDD", "#FFFFFF"],
        badge: "https://api.promiedos.com.ar/images/team/bba/1",
        location: { lat: 53.483, lng: -2.2 },
    },
    {
        id: 3,
        name: "Liverpool",
        country: "England",
        league: "Premier League",
        titles: 19,
        founded: 1892,
        colors: ["#DA291C", "#DA291C"],
        badge: "https://api.promiedos.com.ar/images/team/bai/1",
        location: { lat: 53.4308, lng: -2.9608 },
    },
    {
        id: 4,
        name: "Leeds United",
        country: "England",
        league: "Football League Championship",
        titles: 3,
        founded: 1919,
        colors: ["#1D428A", "#FFCD00"],
        badge: "https://api.promiedos.com.ar/images/team/dg/1",
        location: { lat: 53.7797, lng: -1.5217 },
    },
    {
        id: 5,
        name: "Napoli",
        country: "Italy",
        league: "Serie A",
        titles: 3,
        founded: 1926,
        colors: ["#6CABDD", "#1D428A"],
        badge: "https://api.promiedos.com.ar/images/team/cde/1",
        location: { lat: 40.8533, lng: 14.305 },
    },
    {
        id: 6,
        name: "Roma",
        country: "Italy",
        league: "Serie A",
        titles: 3,
        founded: 1927,
        colors: ["#8e1f2f", "#FFCD00"],
        badge: "https://api.promiedos.com.ar/images/team/ccf/1",
        location: { lat: 41.9028, lng: 12.4534 },
    },
    {
        id: 7,
        name: "Borussia Dortmund",
        country: "Germany",
        league: "Bundesliga",
        titles: 5,
        founded: 1909,
        colors: ["#FDE100", "#000000"],
        badge: "https://api.promiedos.com.ar/images/team/deb/1",
        location: { lat: 51.4925, lng: 7.453 },
    },
    {
        id: 8,
        name: "Flamengo",
        country: "Brazil",
        league: "Brasileirão",
        titles: 7,
        founded: 1895,
        colors: ["#DA291C", "#000000"],
        badge: "https://api.promiedos.com.ar/images/team/bcbf/1",
        location: { lat: -22.9103, lng: -43.22 },
    },
    {
        id: 9,
        name: "Vasco da Gama",
        country: "Brazil",
        league: "Brasileirão",
        titles: 4,
        founded: 1898,
        colors: ["#000000", "#FFFFFF"],
        badge: "https://api.promiedos.com.ar/images/team/bcch/1",
        location: { lat: -22.9101, lng: -43.1765 },
    },
    {
        id: 10,
        name: "Belgrano de Córdoba",
        country: "Argentina",
        league: "Liga Profesional",
        titles: 0,
        founded: 1905,
        colors: ["#6CABDD", "#FFFFFF"],
        badge: "https://api.promiedos.com.ar/images/team/fhid/1",
        location: { lat: -31.413, lng: -64.181 },
    },
    {
        id: 11,
        name: "Talleres",
        country: "Argentina",
        league: "Liga Profesional",
        titles: 0,
        founded: 1913,
        colors: ["#1D428A", "#FFFFFF"],
        badge: "https://api.promiedos.com.ar/images/team/jche/1",
        location: { lat: -31.4037, lng: -64.1937 },
    },
    {
        id: 12,
        name: "Atlético Nacional",
        country: "Colombia",
        league: "Categoría Primera A",
        titles: 16,
        founded: 1947,
        colors: ["#0B6623", "#FFFFFF"],
        badge: "https://api.promiedos.com.ar/images/team/igea/1",
        location: { lat: 6.2419, lng: -75.574 },
    },
    {
        id: 13,
        name: "Millonarios de Bogotá",
        country: "Colombia",
        league: "Categoría Primera A",
        titles: 15,
        founded: 1946,
        colors: ["#1D428A", "#FFFFFF"],
        badge: "https://api.promiedos.com.ar/images/team/igdh/1",
        location: { lat: 4.607, lng: -74.0756 },
    },
    {
        id: 14,
        name: "Corinthians",
        country: "Brazil",
        league: "Brasileirão",
        titles: 7,
        founded: 1910,
        colors: ["#000000", "#FFFFFF"],
        badge: "https://api.promiedos.com.ar/images/team/bcgh/1",
        location: { lat: -23.534, lng: -46.462 },
    },
    {
        id: 15,
        name: "Real Madrid",
        country: "Spain",
        league: "La Liga",
        titles: 35,
        founded: 1902,
        colors: ["#FFFFFF", "#FFFFFF"],
        badge: "https://api.promiedos.com.ar/images/team/bdb/1",
        location: { lat: 40.4531, lng: -3.6883 },
    },
    {
        id: 16,
        name: "Boca Juniors",
        country: "Argentina",
        league: "Liga Profesional",
        titles: 34,
        founded: 1905,
        colors: ["#1D428A", "#FDE100"],
        badge: "https://api.promiedos.com.ar/images/team/igg/1",
        location: { lat: -34.6354, lng: -58.3645 },
    },
    {
        id: 17,
        name: "Rosario Central",
        country: "Argentina",
        league: "Liga Profesional",
        titles: 5,
        founded: 1889,
        colors: ["#1D428A", "#FDE100"],
        badge: "https://api.promiedos.com.ar/images/team/ihf/1",
        location: { "lat": -32.9563, "lng": -60.6500 }
    },
    {
        id: 18,
        name: "Newell's Old Boys",
        country: "Argentina",
        league: "Liga Profesional",
        titles: 6,
        founded: 1903,
        colors: ["#DA291C", "#000000"],
        badge: "https://api.promiedos.com.ar/images/team/ihh/1",
        location: { "lat": -32.9458, "lng": -60.6778 }
    },
    {
        id: 19,
        name: "Gimnasia y Esgrima La Plata",
        country: "Argentina",
        league: "Liga Profesional",
        titles: 0,
        founded: 1887,
        colors: ["#1D428A", "#FFFFFF"],
        badge: "https://api.promiedos.com.ar/images/team/iia/1",
        location: { "lat": -34.9285, "lng": -57.9561 }
    },
    {
        id: 20,
        name: "Racing Club",
        country: "Argentina",
        league: "Liga Profesional",
        titles: 18,
        founded: 1903,
        colors: ["#6CABDD", "#FFFFFF"],
        badge: "https://api.promiedos.com.ar/images/team/ihg/1",
        location: { "lat": -34.5854, "lng": -58.4395 }
    },
    {
        id: 21,
        name: "Instituto de Córdoba",
        country: "Argentina",
        league: "Liga Profesional",
        titles: 1,
        founded: 1918,
        colors: ["#DA291C", "#FFFFFF"],
        badge: "https://api.promiedos.com.ar/images/team/hchc/1",
        location: { "lat": -31.4201, "lng": -64.1888 }
    },
    {
        id: 22,
        name: "Racing de Córdoba",
        country: "Argentina",
        league: "Primera Nacional",
        titles: 1,
        founded: 1956,
        colors: ["#6CABDD", "#FFFFFF"],
        badge: "https://api.promiedos.com.ar/images/team/jcih/1",
        location: { "lat": -31.4136, "lng": -64.1826 }
    },
    {
        id: 23,
        name: "Douglas Haig",
        country: "Argentina",
        league: "Torneo Federal A",
        titles: 1,
        founded: 1921,
        colors: ["#DA291C", "#000000"],
        badge: "https://api.promiedos.com.ar/images/team/jcig/1",
        location: { "lat": -33.2536, "lng": -60.8588 }
    },
    {
        id: 24,
        name: "Sarmiento de Junín",
        country: "Argentina",
        league: "Liga Profesional",
        titles: 1,
        founded: 1911,
        colors: ["#0B6623", "#0B6623"],
        badge: "https://api.promiedos.com.ar/images/team/hbbh/1",
        location: { "lat": -34.5938, "lng": -60.9731 }
    },
    {
        id: 25,
        name: "San Martín de Tucumán",
        country: "Argentina",
        league: "Primera Nacional",
        titles: 3,
        founded: 1909,
        colors: ["#DA291C", "#FFFFFF"],
        badge: "https://api.promiedos.com.ar/images/team/hchb/1",
        location: { "lat": -26.8025, "lng": -65.2222 }
    },
    {
        id: 26,
        name: "Atlético de Madrid",
        country: "Spain",
        league: "La Liga",
        titles: 11,
        founded: 1903,
        colors: ["#DA291C", "#FFFFFF"],
        badge: "https://api.promiedos.com.ar/images/team/bde/1",
        location: { "lat": 40.4637, "lng": -3.5736 }
    },
    {
        id: 27,
        name: "Villarreal CF",
        country: "Spain",
        league: "La Liga",
        titles: 1,
        founded: 1923,
        colors: ["#FDE100", "#FDE100"],
        badge: "https://api.promiedos.com.ar/images/team/bdd/1",
        location: { "lat": 40.0703, "lng": -0.0314 }
    },
    {
        id: 28,
        name: "Inter de Milán",
        country: "Italy",
        league: "Serie A",
        titles: 19,
        founded: 1908,
        colors: ["#1D428A", "#000000"],
        badge: "https://api.promiedos.com.ar/images/team/cce/1",
        location: { "lat": 45.4783, "lng": 9.1193 }
    },
    {
        id: 29,
        name: "Genoa CFC",
        country: "Italy",
        league: "Serie A",
        titles: 9,
        founded: 1893,
        colors: ["#1D428A", "#8e1f2f"],
        badge: "https://api.promiedos.com.ar/images/team/cdb/1",
        location: { "lat": 44.4111, "lng": 8.9329 }
    },
    {
        id: 30,
        name: "Atlético Mineiro",
        country: "Brazil",
        league: "Brasileirão",
        titles: 48,
        founded: 1908,
        colors: ["#000000", "#FFFFFF"],
        badge: "https://api.promiedos.com.ar/images/team/bcaj/1",
        location: { "lat": -19.928, "lng": -43.9378 }
    },
    {
        id: 31,
        name: "Botafogo",
        country: "Brazil",
        league: "Brasileirão",
        titles: 21,
        founded: 1904,
        colors: ["#000000", "#FFFFFF"],
        badge: "https://api.promiedos.com.ar/images/team/bcbb/1",
        location: { "lat": -22.912, "lng": -43.2136 }
    },
    {
        id: 32,
        name: "Vitória",
        country: "Brazil",
        league: "Brasileirão",
        titles: 4,
        founded: 1899,
        colors: ["#DA291C", "#000000"],
        badge: "https://api.promiedos.com.ar/images/team/bcci/1",
        location: { "lat": -12.9714, "lng": -38.5011 }
    },
    {
        id: 33,
        name: "Palmeiras",
        country: "Brazil",
        league: "Brasileirão",
        titles: 11,
        founded: 1914,
        colors: ["#0B6623", "#0B6623"],
        badge: "https://api.promiedos.com.ar/images/team/bccc/1",
        location: { "lat": -23.5345, "lng": -46.7366 }
    },
    {
        id: 34,
        name: "Paysandu SC",
        country: "Brazil",
        league: "Brasileirão Serie B",
        titles: 2,
        founded: 1914,
        colors: ["#6CABDD", "#FFFFFF"],
        badge: "https://api.promiedos.com.ar/images/team/hdja/1",
        location: { "lat": -1.4556, "lng": -48.4897 }
    },
    {
        id: 35,
        name: "Peñarol",
        country: "Uruguay",
        league: "Primera División",
        titles: 69,
        founded: 1891,
        colors: ["#FDE100", "#000000"],
        badge: "https://api.promiedos.com.ar/images/team/hhgg/1",
        location: { "lat": -34.9032, "lng": -56.1651 }
    },
    {
        id: 36,
        name: "Alianza F.C.",
        country: "Colombia",
        league: "Categoría Primera A",
        titles: 0,
        founded: 1982,
        colors: ["#1D428A", "#DA291C"],
        badge: "https://api.promiedos.com.ar/images/team/bacaj/1",
        location: { "lat": 10.4289, "lng": -75.5388 }
    },
    {
        id: 37,
        name: "América de Cali",
        country: "Colombia",
        league: "Categoría Primera A",
        titles: 15,
        founded: 1927,
        colors: ["#DA291C", "#DA291C"],
        badge: "https://api.promiedos.com.ar/images/team/igef/1",
        location: { "lat": 3.4516, "lng": -76.5320 }
    },
    {
        id: 38,
        name: "Bucaramanga",
        country: "Colombia",
        league: "Categoría Primera A",
        titles: 1,
        founded: 1949,
        colors: ["#FDE100", "#0B6623"],
        badge: "https://api.promiedos.com.ar/images/team/bacce/1",
        location: { "lat": 7.1193, "lng": -73.1198 }
    },
    {
        id: 39,
        name: "Deportivo Cali",
        country: "Colombia",
        league: "Categoría Primera A",
        titles: 10,
        founded: 1912,
        colors: ["#0B6623", "#0B6623"],
        badge: "https://api.promiedos.com.ar/images/team/igdj/1",
        location: { "lat": 3.4367, "lng": -76.5223 }
    },
    {
        id: 40,
        name: "Pasto",
        country: "Colombia",
        league: "Categoría Primera A",
        titles: 1,
        founded: 1949,
        colors: ["#1D428A", "#8e1f2f"],
        badge: "https://api.promiedos.com.ar/images/team/jaei/1",
        location: { "lat": 1.2093, "lng": -77.2812 }
    },
    {
        id: 41,
        name: "Pereira",
        country: "Colombia",
        league: "Categoría Primera A",
        titles: 1,
        founded: 1944,
        colors: ["#FDE100", "#DA291C"],
        badge: "https://api.promiedos.com.ar/images/team/igdi/1",
        location: { "lat": 4.8133, "lng": -75.6898 }
    },
    {
        id: 42,
        name: "Junior de Barranquilla",
        country: "Colombia",
        league: "Categoría Primera A",
        titles: 9,
        founded: 1924,
        colors: ["#DA291C", "#FFFFFF"],
        badge: "https://api.promiedos.com.ar/images/team/hcae/1",
        location: { "lat": 10.9687, "lng": -74.7813 }
    },
    {
        id: 43,
        name: "Once Caldas",
        country: "Colombia",
        league: "Categoría Primera A",
        titles: 2,
        founded: 1961,
        colors: ["#FFFFFF", "FFFFFF"],
        badge: "https://api.promiedos.com.ar/images/team/hcij/1",
        location: { "lat": 5.0592, "lng": -75.5176 }
    },
    {
        id: 44,
        name: "Unión Magdalena",
        country: "Colombia",
        league: "Categoría Primera A",
        titles: 1,
        founded: 1951,
        colors: ["#1D428A", "#DA291C"],
        badge: "https://api.promiedos.com.ar/images/team/jidc/1",
        location: { "lat": 11.1898, "lng": -74.1875 }
    },
    {
        id: 45,
        name: "Bayer Leverkusen",
        country: "Germany",
        league: "Bundesliga",
        titles: 1,
        founded: 1904,
        colors: ["#DA291C", "#000000"],
        badge: "https://api.promiedos.com.ar/images/team/ddd/1",
        location: { "lat": 51.0407, "lng": 7.9915 }
    },
    {
        id: 46,
        name: "Celtic FC",
        country: "Scotland",
        league: "Scottish Premiership",
        titles: 51,
        founded: 1887,
        colors: ["#009639", "#FFFFFF"],
        badge: "https://api.promiedos.com.ar/images/team/hfe/1",
        location: { "lat": 55.8608, "lng": -4.2514 }
    },
    {
        id: 47,
        name: "Feyenoord",
        country: "Netherlands",
        league: "Eredivisie",
        titles: 15,
        founded: 1908,
        colors: ["#DA291C", "#FFFFFF"],
        badge: "https://api.promiedos.com.ar/images/team/gjb/1",
        location: { "lat": 51.9225, "lng": 4.4792 }
    },
    {
        id: 48,
        name: "PSV Eindhoven",
        country: "Netherlands",
        league: "Eredivisie",
        titles: 24,
        founded: 1913,
        colors: ["#DA291C", "#FFFFFF"],
        badge: "https://api.promiedos.com.ar/images/team/hcf/1",
        location: { "lat": 51.4416, "lng": 5.4697 }
    },
    {
        id: 49,
        name: "Ajax",
        country: "Netherlands",
        league: "Eredivisie",
        titles: 35,
        founded: 1900,
        colors: ["#DA291C", "#FFFFFF"],
        badge: "https://api.promiedos.com.ar/images/team/gja/1",
        location: { "lat": 52.3774, "lng": 4.8975 }
    },
    {
        id: 50,
        name: "Athletic Club",
        country: "Spain",
        league: "La Liga",
        titles: 8,
        founded: 1898,
        colors: ["#DA291C", "#FFFFFF"],
        badge: "https://api.promiedos.com.ar/images/team/bee/1",
        location: { "lat": 43.2580, "lng": -2.9346 }
    },
    {
        id: 51,
        name: "AZ Alkmaar",
        country: "Netherlands",
        league: "Eredivisie",
        titles: 2,
        founded: 1967,
        colors: ["#DA291C", "#FFFFFF"],
        badge: "https://api.promiedos.com.ar/images/team/gjj/1",
        location: { "lat": 52.4192, "lng": 4.8312 }
    },
    {
        id: 52,
        name: "Beşiktaş",
        country: "Turkey",
        league: "Süper Lig",
        titles: 16,
        founded: 1903,
        colors: ["#000000", "#FFFFFF"],
        badge: "https://api.promiedos.com.ar/images/team/jeh/1",
        location: { "lat": 41.0393, "lng": 29.0274 }
    },
    {
        id: 53,
        name: "Fenerbahçe",
        country: "Turkey",
        league: "Süper Lig",
        titles: 28,
        founded: 1907,
        colors: ["#1D428A", "#FDE100"],
        badge: "https://api.promiedos.com.ar/images/team/jeg/1",
        location: { "lat": 40.9850, "lng": 29.0286 }
    },
    {
        id: 54,
        name: "Galatasaray",
        country: "Turkey",
        league: "Süper Lig",
        titles: 22,
        founded: 1905,
        colors: ["#8e1f2f", "#FFCD00"],
        badge: "https://api.promiedos.com.ar/images/team/jef/1",
        location: { "lat": 41.0101, "lng": 28.9633 }
    },
    {
        id: 55,
        name: "Hoffenheim",
        country: "Germany",
        league: "Bundesliga",
        titles: 0,
        founded: 1945,
        colors: ["#FFFFFF", "#1D428A"],
        badge: "https://api.promiedos.com.ar/images/team/dfb/1",
        location: { "lat": 49.1169, "lng": 8.8072 }
    },
    {
        id: 56,
        name: "Rangers",
        country: "Scotland",
        league: "Scottish Premiership",
        titles: 55,
        founded: 1872,
        colors: ["#1D428A", "#1D428A"],
        badge: "https://api.promiedos.com.ar/images/team/hfd/1",
        location: { "lat": 55.8642, "lng": -4.2518 }
    },
    {
        id: 57,
        name: "Braga",
        country: "Portugal",
        league: "Primeira Liga",
        titles: 4,
        founded: 1921,
        colors: ["#DA291C", "#FFFFFF"],
        badge: "https://api.promiedos.com.ar/images/team/ijf/1",
        location: { "lat": 41.5477, "lng": -8.4291 }
    },
    {
        id: 58,
        name: "Tottenham Hotspur",
        country: "England",
        league: "Premier League",
        titles: 2,
        founded: 1882,
        colors: ["#1D428A", "#FFFFFF"],
        badge: "https://api.promiedos.com.ar/images/team/bbe/1",
        location: { "lat": 51.6043, "lng": -0.0674 }
    },
    {
        id: 59,
        name: "Gent",
        country: "Belgium",
        league: "Pro League",
        titles: 4,
        founded: 1900,
        colors: ["#1D428A", "#FFFFFF"],
        badge: "https://api.promiedos.com.ar/images/team/bbhe/1",
        location: { "lat": 51.0543, "lng": 3.7174 }
    },
    {
        id: 60,
        name: "Noah",
        country: "Armenia",
        league: "Armenian Premier League",
        titles: 0,
        founded: 2017,
        colors: ["#FFFFFF", "#F1C1C1"],
        badge: "https://api.promiedos.com.ar/images/team/fgjdd/1",
        location: { "lat": 40.1517, "lng": 44.4921 }
    },
    {
        id: 61,
        name: "Shamrock Rovers",
        country: "Ireland",
        league: "League of Ireland",
        titles: 18,
        founded: 1901,
        colors: ["#0B6623", "#FFFFFF"],
        badge: "https://api.promiedos.com.ar/images/team/idi/1",
        location: { "lat": 53.2994, "lng": -6.3000 }
    },
    {
        id: 62,
        name: "The New Saints",
        country: "Wales",
        league: "Welsh Premier League",
        titles: 13,
        founded: 1959,
        colors: ["#0B6623", "#FFFFFF"],
        badge: "https://api.promiedos.com.ar/images/team/fgfc/1",
        location: { "lat": 52.9608, "lng": -3.2889 }
    },
    {
        id: 63,
        name: "Vikingur",
        country: "Iceland",
        league: "Úrvalsdeild",
        titles: 3,
        founded: 1911,
        colors: ["#DA291C", "#000000"],
        badge: "https://api.promiedos.com.ar/images/team/cbad/1",
        location: { "lat": 64.1355, "lng": -21.8954 }
    },
    {
        id: 64,
        name: "Bohemian FC",
        country: "Ireland",
        league: "League of Ireland",
        titles: 11,
        founded: 1890,
        colors: ["#DA291C", "#000000"],
        badge: "https://seeklogo.com/images/B/Bohemian_FC-logo-FE54A28FA4-seeklogo.com.png",
        location: { "lat": 53.3586, "lng": -6.2672 }
    },
    {
        id: 65,
        name: "St Patrick's Athletic",
        country: "Ireland",
        league: "League of Ireland",
        titles: 13,
        founded: 1929,
        colors: ["#DA291C", "#FFFFFF"],
        badge: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTdqgofvavQVqkD2_-hp8Zlndzt3rfwG98GZg&s",
        location: { "lat": 53.3499, "lng": -6.2595 }
    }
];

export const minYear = 1850; // Año mínimo
export const maxYear = new Date().getFullYear();

export const colors = [
    {
        value: "Red",
        color: "#DA291C",
    },
    {
        value: "Pink",
        color: "#F1C1C1",
    },
    {
        value: "Light Blue",
        color: "#6CABDD",
    },
    {
        value: "White",
        color: "#FFFFFF",
    },
    {
        value: "Dark Red",
        color: "#8e1f2f",
    },
    {
        value: "Blue",
        color: "#1D428A",
    },
    {
        value: "Yellow",
        color: "#FDE100",
    },
    {
        value: "Black",
        color: "#000000",
    },
    {
        value: "Green",
        color: "#0B6623",
    },
    {
        value: "Gold",
        color: "#FFCD00",
    },
];

export const countryLeagueMap = {
    Spain: ["La Liga"],
    Argentina: ["Liga Profesional", "Primera Nacional", "Torneo Federal A"],
    England: ["Premier League", "Football League Championship"],
    Italy: ["Serie A"],
    Germany: ["Bundesliga"],
    Brazil: ["Brasileirão", "Brasileirão Serie B"],
    Colombia: ["Categoría Primera A"],
    Uruguay: ["Primera División de Uruguay"],
    Scotland: ["Scottish Premiership"],
    Netherlands: ["Eredivisie"],
    Turkey: ["Süper Lig"],
    Portugal: ["Primeira Liga"],
    Belgium: ["Pro League"],
    Armenia: ["Armenian Premier League"],
    Ireland: ["League of Ireland"],
    Wales: ["Welsh Premier League"],
    Iceland: ["Úrvalsdeild"]
};

export const SortBy = {
    NONE: "none",
    NAME: "name",
    COUNTRY: "country",
    LEAGUE: "league",
    FOUNDED: "founded",
    TITLES: "titles",
    BADGE: "badge",
    COLORS: "colors",
    LOCATION: "location"
}
